language: node_js
dist: trusty
node_js:
  - 8
script:
  - node --version
  - yarn --version
  - yarn run test
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && now build --public --token $NOW_TOKEN --name styled-components-website && now alias --token $NOW_TOKEN --force
